#!/usr/bin/env sh

CWDIR=$(cd "$(dirname "$0")"; pwd)

FLUIDHUB_DATAPATH=${CWDIR}/_dev/server/data docker-compose \
-f docker/docker-compose.yml \
-f docker/docker-compose-dev.yml \
-f docker/docker-compose-dev-tests.yml \
run --rm fluidhub-tests $@
