version: "2"

services:
  fluidhub-app:
    build:
      context: ./services
    image: fluidhub-services
    volumes:
      - ./services:/app/services:ro
      - ${FLUIDHUB_DATAPATH}/common:/data/common:rw
      - ${FLUIDHUB_DATAPATH}/wareshub:/data/wareshub:rw
#      - ${FLUIDHUB_DATAPATH}/log:/data/log:rw
    environment:
      - PYTHONPATH=/app/services/fluidhubcommon:$PYTHONPATH
    ports:
      - "3447:3447"
