#!/usr/bin/env sh

if [ -z "$1" ]
then
  echo "Missing path to initialize"
  exit 1
fi


DATA_PATH="$1"

if [ -d "$DATA_PATH" ]
then
  echo "Path $DATA_PATH already exists"
  exit 2
fi



mkdir -p $DATA_PATH
cp -R resources/server-init $DATA_PATH/server
