version: "2"

services:
  fluidhub-tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    image: fluidhub-services-tests
    environment:
      - FLUIDHUB_ADDR=fluidhub-app:3447
      - PYTHONPATH=/fluidhub
    volumes:
      - ../_dev:/_dev:rw
      - ../tests:/tests:rw
      - ../fluidhub/FluidHub:/fluidhub/FluidHub:ro
    links:
      - fluidhub-app
